name: CI/CD - Flask App to AWS ECR & EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python (for linting/tests)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3️⃣ Install dependencies & lint
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8
          flake8 --ignore=E501,F401 .

      # 4️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # ⚙️ Change to your AWS region

      # 5️⃣ Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 6️⃣ Generate version tag
      - name: Set image version
        id: version
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 7️⃣ Build & push Docker image to ECR
      - name: Build and Push Docker Image
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=flask-app
          IMAGE_TAG=${{ env.VERSION }}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # 8️⃣ Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY=flask-app
            IMAGE_TAG=${{ env.VERSION }}

            echo "🚀 Starting EC2 deployment..."

            # --- 1️⃣ Ensure Docker and Git are installed ---
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            if ! command -v git &> /dev/null; then
              echo "Installing Git..."
              sudo apt install -y git
            fi

            if ! command -v python3 &> /dev/null; then
              echo "Installing Python3..."
              sudo apt install -y python3 python3-venv python3-pip
            fi

            # --- 2️⃣ Sync latest GitHub repo ---
            REPO_DIR="/home/ubuntu/Flask-App-GitHub-Actions-ArgoCD"

            if [ ! -d "$REPO_DIR" ]; then
              echo "Cloning repo for the first time..."
              cd /home/ubuntu
              git clone https://github.com/kishoreuppathala5283/Flask-App-GitHub-Actions-ArgoCD.git
              cd "$REPO_DIR"
            else
              echo "Updating existing repo..."
              cd "$REPO_DIR"
              git fetch origin
              git reset --hard origin/main
            fi

            # --- 3️⃣ Create & activate venv, install dependencies ---
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # --- 4️⃣ Authenticate with ECR and deploy Docker container ---
            echo "Logging in to ECR..."
            aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin $ECR_REGISTRY

            echo "Stopping old container (if any)..."
            if [ "$(sudo docker ps -q -f name=flaskapp)" ]; then
              sudo docker stop flaskapp
              sudo docker rm flaskapp
            fi

            echo "Pulling latest image..."
            sudo docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            echo "Starting new container..."
            sudo docker run -d \
              --name flaskapp \
              -p 5000:5000 \
              $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            echo "✅ Deployment completed successfully!"
